### PR TITLE
Fixes for blogposts I created yesterday and today

### PR DESCRIPTION
**Pull request by darrenmeehan**
Hi there @cherbst I noticed you created this fork, are you looking at the blogpost support? Here's a pull request with the changes I've carried out since yesterday. There's still some work to do on updating the display of who likes a blogpost. It seems to be an issue with jQuery updating the html id #users-who-like-. I cant see what is wrong with it just yet, so any help there would be appreciated!

### CODE REVIEW

**Comment by cherbst** [comment]
Yes I was also working on the blogpost support. I will merge this PR and add my work on top of it.

**Comment by darrenmeehan** [comment]
Awesome! What were you working on? I'd appreciate any help you can provide.

**Comment by cherbst** [comment]
Mainly on blogpost integration. I also want to make it configurable which post type can be liked.

**Comment by cherbst** [comment]
I just pushed two commits, one of them is fixing a bug where a users activity update would be deleted.

**Pull request merged**
